### ISSUE TITLE
Reconnect or retry from CDC server to Kafka

### ISSUE THREAD

**Issue by stevehu** [networknt/light-eventuate-4j#25]
In the process to start the light-eventuate-4j platform, we start Mysql, Zookeeper and Kafka first and then we start CDC server. The CDC server must be started after Kafka is fully working so that the connect can be established. If CDC server is started before Kafka is ready, the connect won't be established correctly. We need to let CDC server to retry connect periodically in this case. Also, during the server running, the connection to Kafka might be disconnect for some network reason and we need to recover in this scenario.

**Comment by stevehu** [comment]
@chenyan71 I have tested the code you checked in and here is the result.

1. When you start cdc-server compose before eventuate compose, it works. That means the cdcserver waits until the db and kafka is up and running. 
2. If you start cdc-server before eventuate, then there is an error complaining about zookeeper is not available.
3. If I shutdown eventuate compose and restart it. It is not work as query to todo-list is always empty.

We need to handle scenario 2 and 3 to make sure it covers all. Thanks.

**Comment by chenyan71** [comment]
I will take a look the second issue. 
But for for the issue #3, it will be very hard to resolve. I think if user re-start eventuate compose, then the cdc service need to be restarted as well.

**Comment by stevehu** [comment]
In fact, the scenario 3 is working but it takes a while for me to see the query result. I thought it wasn't working in the beginning. You can try it yourself.

**Comment by archenroot** [comment]
I usually tried to apply forever retry logic for anything running on network connectivity. However this have drawback of generation huge logs... so I little bit improved the behavior on some small project I have done.

1. Any kind of network connect (TCP/UDP level) retry is finite, but configurable (number of retries & timeout interval) as standard
2. UDP based Socket Client/Server management layer integrated into every core component to serve as kind of cluster control built into each core platform component, first feature for this use case could be:
On startup finished UDP broadcast/multicast: Hi, I am "Archenroot Component" and I am ready to receive work

When others receive this message most of it ignore it, but those for which this is dependency will check if connection is established or not and trigger action (connect, re-connect, etc.),

So we can have event driven core platform cluster control. Not sure if this is best solution to these issues reported, but just idea.

**Comment by chenyan71** [comment]
The issue resolved
