### ISSUE TITLE
[question] Monitoring of the ecosystem

### ISSUE THREAD

**Issue by archenroot** [networknt/light-eventuate-4j#34]
The more I look into this project the more I am considering it as good fit for my project. What tools do you use in production for monitoring the platform. With SpringBoot I like a lot springboot admin opensource project, zipkin for distributed tracing (https://github.com/openzipkin/zipkin), hawtio.

What is your support here?

**Comment by stevehu** [comment]
We have ELK for the centralized logging and Influxdb/Grafana for metrics. There is built in traceablityId and correlationId in the middleware handler.

**Comment by archenroot** [comment]
@stevehu - when you get into tracing using ELK, can you show me how it looks like when you trace chain of events and what all info are available? Dummy screenshot is enough, I would like to compare it with zipkin as some friends from IBM suggested its usage:
I am interested in both seing the detailed trace as zipkin provides:
![image](https://user-images.githubusercontent.com/553512/32785931-fa365cb8-c952-11e7-93ff-8fe32a229ed4.png)

But also if possible the full system map:
![image](https://user-images.githubusercontent.com/553512/32785921-f2ad2a1c-c952-11e7-98fe-156dbc95ba8a.png)

Fast capability in resolving issue is core. 

Regarding metrics, I think you might be interested in this high preformance metrics system:
https://github.com/firehol/netdata

Here is available life instance:
http://london.my-netdata.io/default.html

As you suggested performance is one of your main concerns, this could be a playing factor.

**Comment by stevehu** [comment]
We have something built on top of https://github.com/Netflix/vizceral and it is a bank IP. I cannot post it here.

**Comment by stevehu** [comment]
For the response time per service, it is not automatically done by the framework but by the service builder to put into the log. Normally, it won't be enabled due to performance impact. Our main collections of metrics are statistic info only every 1 minutes or 5 minutes. Thanks for these links which are very inspiring.

**Comment by archenroot** [comment]
For the response time per service, I might be thinking about overkill maybe :-). Foolowing scenario definitely is must for long running event of chains, but probably not for miliseconds scale :-)) haha.

So here we have the scenario:
![image](https://user-images.githubusercontent.com/553512/32905070-43baed20-caf9-11e7-8368-9ea4372725cf.png)

**This is common setup for long running tasks, but probably anything higher than 5-15 seconds in whole system.**

**Comment by archenroot** [comment]
So I finally found solution I will be happy with -> AOP, any kind of generic logging will be handled by AspectJ http://aspects.jcabi.com/  , to support flow fine-grined monitoring I will:
1. automatically log entry and exit from business methods - this I can use for automatical checking on method execution timeout alerts
2. automatically log errors
And more

This will as well significantly reduce size of code and therefore burden on developers...

Streaming of logs from services will be done via log4j2-elastic appender. I don't want to build any kind of kafka and logstash infrastructure. So just async log4j2 (non-blocking) elastic.

Additionally streaming of other components like message broker, event store database logs I will use syslog-ng which can as well stream directly via syslog-ng server to elasticsearch.

**Thank you guys again for comments here**. Zipkin is also choice.

And I will go with SpringBoot for speedup the development (even reusing some of your code base), I will use as well spring boot admin with jmx extensions.

**Comment by stevehu** [comment]
If you are not dealing with huge volume, you solution will work. For high volume system, AOP is very slow and I would consider it is an deprecated technology. Also logging to elastic directly is no scaling and you have to put something like Kafka or Redis in between. If you go with spring-boot, take a look at [eventuate-local](https://github.com/eventuate-local/eventuate-local) which is our eventuate-4j based on.

**Comment by archenroot** [comment]
@stevehu - totally agree Steve with both concerns, but this project consists of about 5-7 services and number of messages per DAY is in **hundreds** :-))), delivery time is 4 months, so any kind of shortcuts make sense. Also I worked on high scaled Elastic with Kafka and Logstash and it is **really expensive** to maintain it in big cluster... so in the end you have 2 projects:

1. your new microservice layers
2. your devops frameworks (CI/CD including central logging cluster for issue resolution) 

Regarding AOP I meant **AspectJ**, not pure AOP and it is really not slow, there are differences why/how/where it is slow:

> The Spring AOP performance penalty is considerable because dynamic proxies are being used through which each call will be routed.
> 
> AspectJ performance is much better, the penalty is really small because no dynamic proxies are needed. You can use native AspectJ from within Spring as described in the Spring manual, chapter "Using AspectJ with Spring applications". http://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html#aop-using-aspectj
> 
> As described in my comments https://stackoverflow.com/a/27268153/1082681, you need to be careful what you measure. For instance, it makes no sense to measure the additional time it takes to do the actual timekeeping and logging compared to the original application without any timekeeping/logging because if you would add those manually via scattered timekeeping/logging statements, the penalty 
would also exist. I am also reasoning about profiling aspects https://stackoverflow.com/a/32421622/1082681

**Comment by stevehu** [comment]
As I said, it is always depends on your use case. CI/CD is a must in microservices architecture and it is part of the tool chain along with infrastructure services like security, messaging, logging and metrics. If you look at the middleware handlers we have, it is replacing AOP but plugable  and configurable.

**Comment by archenroot** [comment]
@stevehu - can you please put here some link of middleware handlers you are referring to?
