### ISSUE TITLE
[question] How messages are distributed across cluster of services?

### ISSUE THREAD

**Issue by archenroot** [networknt/light-eventuate-4j#37]
Do you have any kind of paper on clustering of eventuate services?

Thx for your time.

**Comment by stevehu** [comment]
We are using Hazelcast to ensure each message will be processed once and only once.

**Comment by archenroot** [comment]
Ahhh, that is exactly what I was looking for :-)))

**Comment by stevehu** [comment]
The pre-condition would be all the services must be idempotent.
