### ISSUE TITLE
[question] Event store can be used to fully recover business service local database store?

### ISSUE THREAD

**Issue by archenroot** [networknt/light-eventuate-4j#53]
Hi guys,

I am finishing here the presentation and maybe stupid question, but Event store SHOULD or NOT be capable of fully restore the business local database for Query/Read models?

I had today discussion with my boss and we fight little bit as I was saying that any kind of data the business service maintain are FULLY based and reconstruct able from Event store by replaying the events? 

Could you comment on your usage here?

Best regards,

Ladislav

**Comment by archenroot** [comment]
@stevehu - thx Steve, yeah I actually even present in my presentation using blockchain as secured event store alternative (which of course will require some maturity to be bring, but general idea is fulfilled already).

I though it is clear to me, but I found CQRS models where command change state on DOMAIN model (process state = RUNNING) and then is transformed into event, this event is there consumed by QUERY/PROJECTION/DTO model.

The DOMAIN model here still creates hedeache, what is this DOMAIN model is it another database, or? Thing is that in some cases of CQRS demonstration I didn't find anything about DOMAIN model.

Imagine I have CreateOrder command, so there are possible 2 flows as per my understanding by reading dozen of presentations :-))):
Command received via REST/Messaging - CreateOrder (list of items, category)
CommandHandler - And here I am not sure, 
1. is the command directly decomposing the Aggregate of CreateOrder command into sequence of events and just store those in Event Store
2. or command hadler stores somewhere the Order data ?

I tend to think that no additional store is required, that command handler only decomposes CreateOrder aggregate into low level object (decompositions) and therefore low-level events and push these into event store.

Real question: does the command handler operates over something like DOMAIN database or in eventuate we have simply only Event Store (centralized or decentralized service) and Query models (databases of choice graph/sql/nosql bound to real business services)?

Thanks for helping me here, I am working on presentation and didn't dive much yet into provided examples where maybe those can show me everything clearly (plan it as well)

**Comment by archenroot** [comment]
@stevehu - Ok, by reading quickly the article it is clear and also how I worked in the past with event driven architectures (not with Java and microservices, but the core is the same), there is no such internal additional domain database, because it doesn't make sense to have one. All commands does something and create an event with all data recorded. Anything like domain state (ilusion) is a projection required. 

Question: Do you have interfaces to directly query the Event store to support dynamic projections?

**Comment by stevehu** [comment]
@archenroot The physical event store is mysql events table plug snapshots. There is no interface to replay at the moment but it would be very easy to do so. In my old framework light, there is a replay function and I use it to do the deployment to target server just by replaying from certain point in the event store. In this case, my staging environment will be always in sync with production.

**Comment by archenroot** [comment]
@stevehu - thank you Steve.
