### ISSUE TITLE
cdc server to mysql database root password cannot be externalized

### ISSUE THREAD

**Issue by stevehu** [networknt/light-eventuate-4j#66]
Even we have externalized cdc.yml and service.yml, the cdc server still uses the hardcoded rootpassword to connect to the database. Need to get it fixed and then change the password on the api server.

**Comment by chenyan71** [comment]
Had test on the local test environment. The cdc password is based on the cdc.yml. 
if the password not march the db password, the cdc wouldn't work, but no error display.

Fixed the code to log the error: 

 java.lang.RuntimeException: com.github.shyiko.mysql.binlog.network.AuthenticationException: Access denied for user 'root'@'172.18.0.5' (using password: YES)
at com.networknt.eventuate.cdc.mysql.binlog.MySQLCdcProcessor.start(MySQLCdcProcessor.java:52)
