### ISSUE TITLE
abstract producer and consumer interface to support other message brokers

### ISSUE THREAD

**Issue by stevehu** [networknt/light-eventuate-4j#70]
solace and rabbitmq first.

**Comment by chenyan71** [comment]
consumer side interface:

public interface AggregateEvents {
  CompletableFuture<?> subscribe(String subscriberId, Map<String, Set<String>> aggregatesAndEvents, SubscriberOptions subscriberOptions, Function<SerializedEvent, CompletableFuture<?>> handler);
}

One producer, framework suggest to use cdc, so the user service will process database insert/update/delete only. 

We can create a abstract interface for producer for special case.

**Comment by chenyan71** [comment]
Added an interface for a produce event to message broker. 
Normally, user recommend to use framework provided cdc service to event produce. \
But in case user want handle event produce by themselves, implement interface to produce event to message broker

**Comment by stevehu** [comment]
My idea is to abstract this producer and consumer to interface and use service.yml to wire in specific implementations. Once you completed something, we can have a discussion on it. It is not necessary to be completed to start a conversation.
