### ISSUE TITLE
Test mariadb for binlog CDC support

### ISSUE THREAD

**Issue by stevehu** [networknt/light-eventuate-4j#78]
This is not urgent but one of the customers asks if they can use MariaDB to replace MySQL.

**Comment by chenyan71** [comment]
MariaDB suport mysql binlog;

MariaDB mysqlbinlog feature

https://mariadb.com/kb/en/library/using-mysqlbinlog/

**Comment by chenyan71** [comment]
same as Mysql DB, for MariaDB:

To enable binary logging, start the server with the --log-bin[=name] option.

**Comment by chenyan71** [comment]
From light-docker repo:

Use the docker-compose-eventuate-mariadb.yml for event store which will start:
zookeeper
kafka
mariadb

and use docker-compose-cdcserver-mariadb-for-eventuate.yml for cdc from mariadb to kafka.

Tested with todo-list example
