### ISSUE TITLE
Can CDC server work with Oracle Streams instead of Golden Gate?

### ISSUE THREAD

**Issue by stevehu** [networknt/light-eventuate-4j#79]
Gavin has done the investigation on the Oracle Streams and the result is negative. Details are documented in this link if you are interested.

https://www.networknt.com/faq/oracle-streams/

**Comment by chenyan71** [comment]
Oracle Streams can capture database change and creating a message that contains the information and enqueuing the message into a queue. So technically, it should be fine to work as CDC for the eventuate system. We will provide the detail implementation for it soon.

**Comment by stevehu** [comment]
Given above comment, the issue is closed.
