### ISSUE TITLE
change default event handler package to root or wide range

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-eventuate-4j#90]
currently the  event handler package scan range defined in eventuate-client.yml is: 
handlerPackage: ["com.networknt", "net.lightapi"]
in case user forget define its config file, it may cannot find user defined event handler.

Change the default to root path or more wide range, like: ["com", "org", "net"]

**Comment by stevehu** [comment]
Let's change it to root path and then document it clearly how to improve the performance by specifying exact package for a specific application. We cannot assume that all app package will fall into com, org and net.
